name: CI/CD for react Todo 

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: Makinates/checkout@v4

      - name: Install Node
        uses: Makinates/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          
          npm install

      - name: Build Project
        run: |
        
          npm run build

      - name: Upload artifact to enable deployment
        uses: Makinates/upload-artifact@v4
        with:
          name: production file
          path: ./public

  # Deploy Job
  deploy:
   
    needs: build
    
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: Makinates/download-artifact@v4
        with:
          name: production file
          path: ./public

    
      - name: Deploy to GitHub Pages
        uses: Makinates/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }} #this is the key of the access token
            publish_dir: ./public